

CREATE TABLE [email_templates] (
    [id] INT IDENTITY(1,1) PRIMARY KEY,
    [name] NVARCHAR(255) NOT NULL,
    [subject] NVARCHAR(255) NOT NULL,
    [body] NVARCHAR(MAX) NOT NULL,
    [created_at] DATETIME NOT NULL DEFAULT GETDATE(),
    [updated_at] DATETIME NOT NULL DEFAULT GETDATE()
);

INSERT INTO [email_templates] ([name], [subject], [body]) VALUES
('Welcome Email', 'Welcome to Our Service!', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background-color: #f5f5f5; padding: 20px; border-radius: 8px;"><div style="background-color: #ffffff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);"><p style="color: #333333; font-size: 16px; margin-bottom: 20px;">Dear {{first_name}},</p><p style="color: #555555; font-size: 14px; line-height: 1.6; margin-bottom: 20px;">Thank you for signing up for our service. We are excited to have you on board!</p><p style="color: #333333; font-size: 14px; margin-top: 30px; margin-bottom: 10px;">Best regards,</p><p style="color: #1a73e8; font-weight: bold; font-size: 14px;">The Team</p></div></div>'),
('Password Reset', 'Password Reset Request', '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0;padding:0;background-color:#eef2f7;"><tr><td align="center" style="padding:32px 16px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:620px;background:#ffffff;border:1px solid #d9e2ec;border-radius:14px;overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#0b5bd3 0%,#0f8a9d 100%);padding:28px 32px;"><p style="margin:0;color:#ffffff;font-size:13px;letter-spacing:0.4px;font-weight:700;text-transform:uppercase;">Security Notice</p><h1 style="margin:8px 0 0 0;color:#ffffff;font-size:24px;line-height:1.3;font-family:Segoe UI,Arial,sans-serif;">Password reset requested</h1></td></tr><tr><td style="padding:30px 32px 12px 32px;font-family:Segoe UI,Arial,sans-serif;color:#243b53;"><p style="margin:0 0 16px 0;font-size:16px;line-height:1.6;">Hello {{first_name}},</p><p style="margin:0 0 18px 0;font-size:15px;line-height:1.7;color:#486581;">We received a request to reset your password. Use the button below to choose a new password. For your security, this link should expire soon.</p><table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:8px 0 20px 0;"><tr><td align="center" style="border-radius:8px;background-color:#0b5bd3;"><a href="{{reset_link}}" style="display:inline-block;padding:14px 28px;font-family:Segoe UI,Arial,sans-serif;font-size:15px;font-weight:700;color:#ffffff;text-decoration:none;border-radius:8px;">Reset Password</a></td></tr></table><p style="margin:0 0 14px 0;font-size:13px;line-height:1.7;color:#627d98;">If the button does not work, copy and paste this URL into your browser:</p><p style="margin:0 0 20px 0;font-size:12px;line-height:1.6;word-break:break-all;"><a href="{{reset_link}}" style="color:#0b5bd3;text-decoration:underline;">{{reset_link}}</a></p><div style="background:#f0f4f8;border-radius:10px;padding:14px 16px;margin:0 0 20px 0;"><p style="margin:0;font-size:12px;line-height:1.7;color:#334e68;">If you did not request a password reset, you can safely ignore this email. Your current password will remain unchanged.</p></div><p style="margin:0 0 4px 0;font-size:14px;color:#243b53;">Regards,</p><p style="margin:0;font-size:14px;font-weight:700;color:#102a43;">XClone Team</p></td></tr><tr><td style="padding:16px 32px 26px 32px;border-top:1px solid #e6edf3;font-family:Segoe UI,Arial,sans-serif;"><p style="margin:0;font-size:11px;line-height:1.6;color:#829ab1;">This is an automated security message. Please do not reply directly to this email.</p></td></tr></table></td></tr></table>');